# Generated by Django 4.0.4 on 2022-05-09 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='category',
            field=models.CharField(choices=[(1, '상품 문의'), (2, '교환&환불 문의'), (3, '배송 문의')], default=1, max_length=10, verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='최종 수정 일시'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='title',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='제목'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('상품 문의', '상품 문의'), ('교환&환불 문의', '교환&환불 문의'), ('배송 문의', '배송 문의')], default=1, max_length=10, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='제목'),
        ),
    ]
