# Generated by Django 4.0.4 on 2022-05-10 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_answer_alter_faq_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.TextField(default='', verbose_name='답변내용'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='최종 수정 일시'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='inquiry',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='support.inquiry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='phoneNum',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('1', '상품 문의'), ('2', '교환&환불 문의'), ('3', '배송 문의')], default=1, max_length=10, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='최종 수정 일시'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='category',
            field=models.CharField(choices=[('1', '상품 문의'), ('2', '교환&환불 문의'), ('3', '배송 문의')], default=1, max_length=10, verbose_name='카테고리'),
        ),
    ]
